### PR TITLE
feat: document severity level parameters

### PR DESCRIPTION
**Pull request by baturayo**
- document severity level parameters

### CODE REVIEW

**Review by janet-can — APPROVED** [review]

**Comment by bastienboutonnet** [comment]
CleanShot 2024-01-29 at 12 27 28@2x

**Comment by bastienboutonnet** [comment]
CleanShot 2024-01-29 at 12 30 07@2x

**Comment by bastienboutonnet** [comment]
CleanShot 2024-01-29 at 12 44 42@2x

**Review by bastienboutonnet — APPROVED** [review]
Approved from my side

Here's a "shipit cat" (it's a cat most of the time) but I am at the mercy of the randomisation gods.

**Review by janet-can — APPROVED** [review]

**Pull request merged**
