### PR TITLE
add reporting API v1 docs

### PR DESCRIPTION
**Pull request by bastienboutonnet**
Resolves: https://sodadata.atlassian.net/browse/CLOUD-1739

### CODE REVIEW

**Review by janet-can — APPROVED** [review]
Migration guide/what's changed is good to go.
At some point later, I wouldn't mind editing the explanatory copy for each endpoint to conform all language to the docs style guide, but it's not a blocker for moving forward.

**Comment by janet-can** [comment]
Four tasks to complete before publishing:

1. Unless you visit the Overview page, which includes the word "Preview" in the title and a small `v1.0.0a16` tag, it is not obvious in the docs that what you are seeing is stuff that is a) v1, and b) preview. Is it possible to:
a) add the v.1.0.0a16 to each page, and
b) include the word preview in each Endpoint's title? 
Readers can land on any page in the API docs and we owe it to them to make sure they have the right info about what they are accessing.

2. Complete a) for version 0 docs as well. Ideally, that little tag would appear on each page of API docs associated with its version.

3. Fix the left-padding issue. @bastienboutonnet is that something I should ask Andres for help to do?

4. Include the version in the breadcrumb. I'm not exactly sure how to do this; in docs, I normally set the breadcrumb for a page in the header content as the value for "parent". We should do this for both version 0 and version 1.
Screen Shot 2022-12-01 at 10 50 54 AM

**Comment by bastienboutonnet** [comment]
> 1. Unless you visit the Overview page, which includes the word "Preview" in the title and a small v1.0.0a16 tag, it is not obvious in the docs that what you are seeing is stuff that is a) v1, and b) preview. Is it possible to:
a) add the v.1.0.0a16 to each page, and
b) include the word preview in each Endpoint's title?
Readers can land on any page in the API docs and we owe it to them to make sure they have the right info about what they are accessing.

- Now that I've modified the breakdcrum, I think what we have is pretty good IMO. I think exact version tag is overkill for all pages, and it's not possible to do it since we're using a framework called stoplight that makes choices on how it renders the API docs.

- Adding the word preview to each endpoint title is possible. Tediuous and IMO overkill but possible.

Right now we have the word preview already all over the place I feel:
Screenshot 2022-12-01 at 21 34 39

> 2. Complete a) for version 0 docs as well. Ideally, that little tag would appear on each page of API docs associated with its version.

As far as I know it can't happen.

> 3. Fix the left-padding issue. @bastienboutonnet is that something I should ask Andres for help to do?

I have no idea, maybe? I dont know his skill set and what our relationship and how we pass on work to him is like so I can't tell. If a frontender should look into this, I would check with Benjamin to get an issue created and brought forward in sprint planning. I would however say this is not a blocker for exposing the documentation and is out of the scope of this PR which should, IMO, restrict itself to content changes related to v1 and whatever we can do to make the version clear with what we have.

> 4. Include the version in the breadcrumb. I'm not exactly sure how to do this; in docs, I normally set the breadcrumb for a page in the header content as the value for "parent". We should do this for both version 0 and version 1.

Done, good idea!

**Comment by janet-can** [comment]
> Adding the word preview to each endpoint title is possible. Tediuous and IMO overkill but possible.
1. I don't disagree, because if you're looking for the version number, you will see it. But if you do a search in the docs or Google and simply land on a page, you might not immediately notice that it is relevant only for v1 of the API vs. v0. Part of the Every Page is Page One (EPPO) approach to docs demands that we think about each page as a landing page for a reader and give them the context to know where they are and how what they are reading fits into a bigger picture.  A non-zero amount of tedium occurs, but it's worth the payoff to search-result landers.
@bastienboutonnet I can go through and add it to the pages if you point me to the correct file?

2. OK. Limitations gonna be limitations.

3. I'll pull this aside and fix ASAP outside this PR. It's pretty awful on the mobile version! Consider this an IGNORE for this PR.

4. Merci!

**Comment by janet-can** [comment]
Fixed the left-padding issue in a separate PR. Alls we need now is that preview notation on v1 pages and we're good to go!

**Pull request merged**
