### PR TITLE
Docs distributions update

### PR DESCRIPTION
**Pull request by tituskx**
Created a new section that documents how you can fix the errors associated with installing soda-core-scientific. @janet-can you and I could go over this together to make sure it works on your system too. Currently, the section is written as a short debug manual for people that run into these errors. However, I would propose that we add these instructions to the Install Soda Core Scientific section before pip install soda-core-scientific is run, so that the errors do not show up at all. Both pystan and prophet are installed using the setup.py install method because the wheels are broken.

Partially addresses: https://sodadata.atlassian.net/browse/SODA-461
Resolves: https://sodadata.atlassian.net/browse/SODA-169

### CODE REVIEW

**Comment by tituskx** [comment]
@janet-can Hey Janet, would it make sense to have a dedicated "installation problems" page that deals with bugs that occur frequently while trying to install soda scientific, instead of having it on the distribution checks page?

**Comment by janet-can** [comment]
> @janet-can Hey Janet, would it make sense to have a dedicated "installation problems" page that deals with bugs that occur frequently while trying to install soda scientific, instead of having it on the distribution checks page?

That's a really good question. I think the answer is, "it depends". 

If soda-core-scientific is only required for the two checks, anomaly and distribution, _and_ the installation involves one or perhaps two steps to install (pip install aaa, pip install soda-core-scientific), then I would say that we should keep the install as simply a quick prerequisite for those two checks. We can even make it an _include file in docs so that there is one file containing the content and it just gets served in two or more places, thereby preserving a single-source-of-truth.

If, however, we anticipate using soda-core-scientific for more checks in the future and/or there are potentially more than one or two steps to install it, then I would argue that it should have its own page. I'm a little less inclined to go this route for now as its use is so specialized/limited at present. 

I suppose that given what we know right now, I would argue that we should pursue the former approach. We can always shift to the latter if/when soda-core-scientific becomes more widely used for a bunch of things.

Make sense?

**Comment by bastienboutonnet** [comment]
@janet-can considering that the installation instructions of the sci library will be a little lengthy meaning that:
- we will have to explain the happy path installation (i.e. do `pip install` and it should work)
- an explanation of using docker if things don't work out with pip install
- and some potential workarounds a bit like the ones proposed in this PR

I think we should indeed have a include strategy at the very least, but given the length of it I'm thinking it might quickly warrant its own page, unless we can do some expand-like behaviours. What do you think?

**Comment by bastienboutonnet** [comment]
Because I had to write some instructions for the usage of Soda Core in Docker, I've gone ahead and:
- added an include file that we can use to append to all check docs that depend on the scientific library
- moved the installation steps from @tituskx in there as well.

These changes are applied in: https://github.com/sodadata/docs/pull/265 which should be merged **into this PR** if no further changes are required and then this PR should be merged to main.

**Comment by bastienboutonnet** [comment]
@tituskx could you make sure to update this branch and resolve conflicts so that if https://github.com/sodadata/docs/pull/265 is approved by @janet-can we can merge it into here and mark this PR as ready to review as well.

**Review by janet-can — APPROVED** [review]

**Pull request merged**
