### PR TITLE
feat: document anomaly detection simulator

### PR DESCRIPTION
**Pull request by baturayo**

### CODE REVIEW

**Review by janet-can — APPROVED** [review]
Cool, this is going to be great!
I change the install and run section to make it into an ordered list procedure, and adjust the images so they had borders and obfuscated values. 
I shortened the content for each parameter adjustment section because it rather repeated what was already explained in other sections, so I just kept the links with a few extra details.

**Comment by bastienboutonnet** [comment]
@baturayo 
CleanShot 2024-02-07 at 11 07 02@2x

**Comment by bastienboutonnet** [comment]
@baturayo 
CleanShot 2024-02-07 at 11 08 53@2x

**Comment by bastienboutonnet** [comment]
CleanShot 2024-02-07 at 11 09 45@2x

**Comment by bastienboutonnet** [comment]
CleanShot 2024-02-07 at 11 10 38@2x

**Comment by bastienboutonnet** [comment]
Image broken: 
CleanShot 2024-02-08 at 09 15 36@2x

**Comment by bastienboutonnet** [comment]
maybe a more zoomed in image would help: 
CleanShot 2024-02-08 at 09 16 20@2x

**Comment by baturayo** [comment]
> maybe a more zoomed in image would help: CleanShot 2024-02-08 at 09 16 20@2x

Unfortunately increasing the height and width of the image didn't increase the size. I think the docs has a fixed layout. For me the current image gives an idea about how the welcome screen look like. Wdyt? Can we leave it like this?

**Review by bastienboutonnet — APPROVED** [review]
Let's go!

Here's a "shipit cat" (it's a cat most of the time) but I am at the mercy of the randomisation gods.

**Pull request merged**
